name: "Kind MacOS K8s Cluster"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      wescale_image_tag:
        description: "WeScale Image Tag"
        required: true
        default: "0.3.0"
      wesql_image_tag:
        description: "WeSQL Server Image Tag"
        required: true
        default: "8.0.35-6.alpha10.20240918.g18ad68b.27"

jobs:
  setup:
    name: "Setup WeScale WeSQL Server Cluster"
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Install Docker
      - name: Install Docker
        run: brew install --cask docker

      # Step 4: Start Docker
      - name: Start Docker
        run: |
          open /Applications/Docker.app
          # 等待 Docker 完全启动
          sleep 60

      # Step 5: Install kubectl
      - name: Install kubectl
        run: brew install kubectl

      # Step 6: Install Kind
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-darwin-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Step 7: Create Kind Cluster
      - name: Create Kind Cluster
        run: kind create cluster --name wescale-cluster

      - name: kubectl get nodes
        run: |
          kubectl get nodes
          kubectl get pods -A