name: "Setup WeScale WeSQL Server Cluster2"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      wescale_image_tag:
        description: "WeScale Image Tag"
        required: true
        default: "0.3.0"
      wesql_image_tag:
        description: "WeSQL Server Image Tag"
        required: true
        default: "8.0.35-6.alpha10.20240918.g18ad68b.27"

jobs:
  setup:
    name: "Setup WeScale WeSQL Server Cluster"
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Homebrew (如果未预装)
      - name: Install Homebrew
        if: runner.os == 'macos' && !command -v brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      # Step 3: Install kubectl
      - name: Install kubectl
        run: brew install kubectl

      # Step 4: Install Docker CLI
      - name: Install Docker CLI
        run: brew install docker

      # Step 5: Install Colima
      - name: Install Colima
        run: brew install colima

      # Step 6: Start Docker
      - name: Start Docker
        run: |
          brew services start docker
          # 等待 Docker 完全启动
          for i in {1..10}; do
            if docker info > /dev/null 2>&1; then
              echo "Docker is running"
              break
            else
              echo "Waiting for Docker to start..."
              sleep 5
            fi
          done

      # Step 7: Start Colima with Kubernetes using Docker runtime
      - name: Start Colima with Kubernetes
        run: |
          colima start --kubernetes --docker
          # 等待 Colima 和 Kubernetes 完全启动
          for i in {1..10}; do
            if kubectl cluster-info > /dev/null 2>&1; then
              echo "Kubernetes is running"
              break
            else
              echo "Waiting for Kubernetes to start..."
              sleep 5
            fi
          done

      # Step 8: Verify Kubernetes is running
      - name: Verify Kubernetes is running
        run: |
          kubectl get nodes
          kubectl get pods -A
